### ISSUE TITLE
Error with offset

### ISSUE THREAD

**Issue by demonenf** [wix-incubator/DeviantArt-API#125]
In the docs can read:
GET offset (integer) : The pagination offset
optional   min: 0 max: 50000 default: 0 

If you use limit=10&offset=10000 it works and read the has_more=true, next_offset=10010 and the results' array containing 10 deviations. BUT if you use limit=10&offset=10001 nothing is returned even if you have seen that there are more deviations.

Also from web gallery with URL "...art.com/gallery/?catpath=/&offset=10000" you can see the results, but the same URL changed offset to 10001 shows "This section has no deviations yet!"

**Comment by zachweinstein** [comment]
Hi there, I know this is an old thread, but I'm actually running into this same problem myself. For galleries larger than 9999 deviations, it is impossible to grab any past that number. Hoping that my bumping of this issue will lead it to being solved.

**Comment by zachweinstein** [comment]
This is still broken after nearly 5 years.

**Comment by aaronpearce** [comment]
Could you please leave a example of a gallery where this occurs? Preferably the link to the console for this call.

**Comment by zachweinstein** [comment]
> Could you please leave a example of a gallery where this occurs? Preferably the link to the console for this call.

For my own privacy, I'd prefer not to give a gallery, but I can give you the calls being used and what they return.

`https://www.deviantart.com/api/v1/oauth2/collections/[folderid]?offset=[offset]&limit=1&mature_content=true&access_token=[access_token]&username=[username]`

For any offset value over 9999, it will respond with "This section has no deviations yet!", regardless of what you set the limit to. However, this call works perfectly fine with every value below 10,000. This is problematic because my application grabs a random deviation from any given collection/gallery using some value between 0 and the total size of the collection/gallery (in many cases, over 9999).

**Comment by indoorstereo** [comment]
I've also run into this issue. It happened to me in the `/browse/tags` endpoint as well as the `/collections/{folderid}` endpoint, so I assume it's common across any request with an offset > 10,000. 

The exact point at which the API stops returning results varies and seems random, though I've never been able to get further than 10,000. Normally it breaks in the 9800 to 10,000 range.

Here's an example using a random folder I found. It contains 10k deviations. Funny enough, in testing this specific folder, I couldn't even get passed 540.

`https://www.deviantart.com/api/v1/oauth2/collections/ED39828B-6764-BD7D-EE09-61239857045F?username=edwarddepp&offset=1000&limit=10&with_session=false&mature_content=true`

**Comment by aaronpearce** [comment]
Paging is only available to that depth. Sorry for the inconvenience.
