### ISSUE TITLE
Increase Access and Refresh Tokens Lifespan

### ISSUE THREAD

**Issue by No767** [wix-incubator/DeviantArt-API#193]
I've noticed that the access tokens and refresh tokens only last for 1 hour. This means that every hour I have to contact the token endpoint in order to refresh the tokens, which becomes annoying to do. I'm just wondering why does only last for 1 hour, and could it be extended to 1 month instead. (Pinterest has their access and refresh token's lifespan set to 1 month, and I am wondering why DeviantArt couldn't do the same)

**Comment by JakeyPrime** [comment]
+1

**Comment by aaronpearce** [comment]
Hi,

At this time, we will not be changing the expiration time of access tokens. 

Refreshing the token every hour is the expected behaviour and your code should be developed to manage this requirement. 

Please refer to the [Authentication](https://www.deviantart.com/developers/authentication) page of our API documentation for more on refreshing your existing tokens.
