### ISSUE TITLE
Replacement for removed /browse API endpoints

### ISSUE THREAD

**Issue by mhanapole** [wix-incubator/DeviantArt-API#248]
I have a small web app for personal use that I'm using the API for, which was using the /browse/deviantsyouwatch, /browse/popular, /browse/newest, and /browse/recommended API endpoints. It appears that there was an update on July 1st that removed these endpoints.

I see the /browse/deviantsyouwatch was readded as a result of this issue https://github.com/wix-incubator/DeviantArt-API/issues/244 and that one is now working as expected, but the others are missing.

Is there a way I can achieve the functionality of these removed endpoints with the new API version?

**Comment by DineshSolanki** [comment]
Looking for the same to search, earlier using browse/newest

**Comment by sasha-lerner** [comment]
please use endpoint browse/home - it is a recommended feed, same as on da homepage
the other sort orders are no longer supported and have not been for some time

**Comment by DineshSolanki** [comment]
@sasha-lerner If I'm not wrong, browse/home has no query parameter for search, how do we search for a specific title, say Harry Potter, the browse/popular had one

**Comment by DineshSolanki** [comment]
@sasha-lerner Interestingly today I see the query parameter in documentation and it works in DeviantART API console, however when I use my access_token to access it, it always says `Expired oAuth2 user token. The client should request a new one with an access code or a refresh token.` even though the placebo call says token is valid and other endpoints also works with it.
I suppose this is because the following statement 
![image](https://github.com/user-attachments/assets/0f62861b-6d47-482b-a59f-e97183841643)

shouldn't this also be accessible with `access_token` acquired from `client_credentials` grant just as browse/popular and browse/newest did?

Here's how I get the token - 
```csharp
https://www.deviantart.com/oauth2/token?client_id={ClientId}&client_secret={ClientSecret}&grant_type=client_credentials"
```

and how I use it in browser/home 
```csharp
https://www.deviantart.com/api/v1/oauth2/browse/home?offset={offset}&q={query}&limit=20&access_token={ClientAccessToken}

**Comment by DineshSolanki** [comment]
Seems like all these changes are done, though would appreciate a notification on change✌️
![image](https://github.com/user-attachments/assets/337607bc-a53c-43d3-be20-2461d41bf10a)
